from:
  db_type: mysql
  host: 127.0.0.1
  port: 13306
  user: root
  pwd: '123456'
  database: lalala
  tables:
    - student:
        - id
        - name
        - age
    - teacher:
        - id
        - name
        - age

to:
  db_type: postgresql
  host: 127.0.0.1
  port: 15432
  user: postgres
  pwd: '123456'
  database: test
  tables:
    - lalala:
        - id
        - name
        - age