from:
  db_type: mysql
  host: 39.96.71.34
  port: 3306
  user: aicyber
  pwd: Aicyber201415926
  database: cloud
  tables:
    - app:
        - id
        - addtime
        - name
        - key
        - type
        - login_url
        - callback_url
        - mns
    - call:
        - id
        - addtime
        - from
        - to
        - type
        - taskid
        - timeout
        - transfer_line
        - transfer_number
    - callback:
        - id
        - addtime
        - appid
        - type
        - data
    - callin:
        - id
        - addtime
        - appid
        - tag
        - number
        - flow_token
        - flow_id
        - limit
        - enabled
        - enabled_time
        - transfer_line
    - corp:
        - id
        - addtime
        - name
        - domain
        - type
        - pid
        - flow_ticket
        - flow_token
    - group:
        - id
        - addtime
        - name
        - type
        - corpid
    - line:
        - id
        - addtime
        - tag
        - limit
        - enabled
        - ip
        - port
        - user
        - pwd
        - status
    - permission:
        - id
        - addtime
        - appid
        - groupid
        - name
    - seat:
        - id
        - addtime
        - appid
        - number
        - tag
        - enabled
    - user:
        - id
        - addtime
        - name
        - mobile
        - email
        - pwd
        - salt
        - groupid
        - corpid
        - properties
        - key
    - verify:
        - id
        - addtime
        - mobile
        - code
        - action
        - now
        - timeout
        - try
        - try_limit
        - ip
        - used
to:
  db_type: postgresql
  host: aicyber007.pg.rds.aliyuncs.com
  port: 3433
  user: postgres
  pwd: Z8asuidn
  database: cloud
  tables:
    - cloud_app:
        - id
        - addtime
        - name
        - key
        - type
        - login_url
        - callback_url
        - mns
    - cloud_call:
        - id
        - addtime
        - from
        - to
        - type
        - taskid
        - timeout
        - transfer_line
        - transfer_number
    - cloud_callback:
        - id
        - addtime
        - appid
        - type
        - data
    - cloud_callin:
        - id
        - addtime
        - appid
        - tag
        - number
        - flow_token
        - flow_id
        - limit
        - enabled
        - enabled_time
        - transfer_line
    - cloud_corp:
        - id
        - addtime
        - name
        - domain
        - type
        - pid
        - flow_ticket
        - flow_token
    - cloud_group:
        - id
        - addtime
        - name
        - type
        - corpid
    - cloud_line:
        - id
        - addtime
        - tag
        - limit
        - enabled
        - ip
        - port
        - user
        - pwd
        - status
    - cloud_permission:
        - id
        - addtime
        - appid
        - groupid
        - name
    - cloud_seat:
        - id
        - addtime
        - appid
        - number
        - tag
        - enabled
    - cloud_user:
        - id
        - addtime
        - name
        - mobile
        - email
        - pwd
        - salt
        - groupid
        - corpid
        - properties
        - key
    - cloud_verify:
        - id
        - addtime
        - mobile
        - code
        - action
        - now
        - timeout
        - try
        - try_limit
        - ip
        - used